export * from './addExistMember.test'
export * from './addExistOtherClubMember.test'
export * from './addMultipleMember.test'
export * from './addNewMember.test'
export * from './addOtherCommMember.test'
export * from './addToNoneClub.test'
export * from './blockedTrying'
