CREATE TABLE `files` (
	fileOId CHAR(24) PRIMARY KEY,

  content MEDIUMTEXT,
  dirOId CHAR(24) NOT NULL,

  fileIdx INT UNSIGNED NOT NULL,
  fileName VARCHAR(64) NOT NULL,
  fileStatus TINYINT UNSIGNED NOT NULL DEFAULT 0,

  userName VARCHAR(30) NOT NULL,
  userOId CHAR(24) NOT NULL,

  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;